name: Post welcome comment
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
  job2:
    name: sample additional job
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an nother job"
  job3:
    name: new additional job
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job3"
      
